services:
  app:
    image: leonardonicola/readx
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
      soketi:
        condition: service_started
    profiles: [dev]

  # Integration tests DB
  db-integration:
    image: postgres:16.4
    container_name: integration
    environment:
      POSTGRES_DB: integration_db
      POSTGRES_USER: integration_user
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d integration_db -U integration_user"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    profiles: [integration]
  db:
    image: postgres:16.4
    container_name: ${DB_NAME}_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles: [dev, db]
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123
    depends_on:
      - db
    profiles: [db]
volumes:
  pgdata:
