services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: readx
      POSTGRES_USER: popinjay
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U popinjay -d readx'"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: