name: Tests
on:
  pull_request:
    branches:
      - main
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.github/actions/build
      - uses: ./.github/actions/docker-compose
      - name: Run integration tests
        run: bun test:integration

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.github/actions/build
      - name: Run unit tests
        run: bun test:unit
env:
  DATABASE_URL: postgres://admin:SuperSecret123@localhost:5432/readx
  DB_USER: admin
  DB_NAME: readx
  DB_PASS: SuperSecret123
