name: Tests
on:
  pull_request:
    branches:
      - main
  jobs:
    unit-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          name: Checkout

        - uses: pnpm/action-setup@v4
          name: Install pnpm
          with:
            version: 9
            run_install: false

        - uses: actions/setup-node@v4
          name: Install Node.js
          with:
            node-version: 20
            cache: "pnpm"

        - name: Install dependencies
          run: pnpm install

        - name: Run unit tests
          run: pnpm test:unit
