name: Tests
on:
  pull_request:
    branches:
      - main
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.github/actions/build
      - name: Run integration tests
        run: pnpm test:integration

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.github/actions/build
      - name: Run unit tests
        run: pnpm test:unit
env:
  DATABASE_URL: postgres://readx:SuperSecret123@localhost:5432/readx_db
  DB_USER: readx
  DB_NAME: readx_db
  DB_PASS: SuperSecret123
